name: Build and deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://vgeorge.azurecr.io/
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD  }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: vgeorge.azurecr.io/${{ secrets.USERNAME }}/cscicdwebapplication:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:    
            
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: vgeorge.azurecr.io/${{ secrets.USERNAME }}/cscicdwebapplication:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: vgeorge.azurecr.io
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: cscicdwebapplication
            location: 'east us'
