on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.SP_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: vgeorge.azurecr.io
            username: ${{ secrets.SP_ID }}
            password: ${{ secrets.SP_SECRET }}
        - run: |
            docker build . -t vgeorge.azurecr.io/cscicdwebapplication:${{ github.sha }}
            docker push vgeorge.azurecr.io/cscicdwebapplication:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: rg.containers
            dns-name-label: cscicdwebapplication-${{ github.run_number }}
            image: vgeorge.azurecr.io/cscicdwebapplication:${{ github.sha }}
            registry-login-server: vgeorge.azurecr.io
            registry-username: ${{ secrets.SP_ID }}
            registry-password: ${{ secrets.SP_SECRET }}
            name: cscicdwebapplication
            location: 'east us'
