name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: vgeorge.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build . -t vgeorge.azurecr.io/cscicdwebapplication:${{ github.sha }}
          docker push vgeorge.azurecr.io/cscicdwebapplication:${{ github.sha }}
      
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: vgeorge.azurecr.io/cscicdwebapplication:${{ github.sha }}
            registry-login-server: vgeorge.azurecr.io
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: cscicdwebapplication
            location: 'east us'
