name: Build and deploy container

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: Log in to registry
          uses: docker/login-action@v1
          with:
            registry: https://vgeorge.azurecr.io/
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

        - name: Build and push container image to registry
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: vgeorge.azurecr.io/cscicdwebapplication:${{ github.sha }}
            file: ./Dockerfile
        
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.SP_CREDENTIALS }}
        
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: rg.containers
            dns-name-label: cscicdwebapplication-${{ github.run_number }}
            image: vgeorge.azurecr.io/cscicdwebapplication:${{ github.sha }}
            registry-login-server: vgeorge.azurecr.io
            registry-username: ${{ secrets.SP_ID }}
            registry-password: ${{ secrets.SP_SECRET }}
            name: cscicdwebapplication
            location: 'east us'
