# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cscicd

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://crcicd.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_98213911303243c1a171583f88052d4b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6782d49516404d008fb58a05aca418ed }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: crcicd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_98213911303243c1a171583f88052d4b }}/cscicdwebapplication:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cscicd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7fc58051207b426593a7899f6d350d52 }}
        images: 'crcicd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_98213911303243c1a171583f88052d4b }}/cscicdwebapplication:${{ github.sha }}'